name: egamebook_builder
description: Builders for egamebook.
version: 1.0.0
# homepage: https://www.example.com
# author: Filip Hracek <email@example.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  build: any # ^0.12.7+3
  built_value: any # ^6.0.0
  code_builder: any
  dart_style: any
  glob: any # ^1.1.7
  source_gen: ^0.8.3+1 # ^0.9.0

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
